Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Ansible.VM
  config.vm.define "alma9" do |alma9|
    alma9.vm.box = "almalinux/9"
    alma9.vm.hostname = "alma9"
	alma9.vm.network "private_network", ip: "192.168.56.30"
  end
end  
