Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Ansible.VM
  config.vm.define "srv_1" do |srv_1|
    srv_1.vm.box = "ubuntu/bionic64"
    srv_1.vm.hostname = "srv1"
	srv_1.vm.network "private_network", ip: "192.168.56.21"
  end

### Ansible2.VM
  config.vm.define "srv_2" do |srv_2|
    srv_2.vm.box = "geerlingguy/centos7"
	  srv_2.vm.hostname = "srv2"
  srv_2.vm.network "private_network", ip: "192.168.56.22"
  end
end  
